CREATE TABLE IF NOT EXISTS user(
	fb_name VARCHAR(50) NOT NULL,
	fb_id BIGINT(64) UNSIGNED NOT NULL,
	fb_profile_pic_path VARCHAR(100) NOT NULL
);

ALTER TABLE user DROP COLUMN fb_profile_pic_path;
ALTER TABLE user ADD COLUMN role TINYINT(1) UNSIGNED DEFAULT 2;